-- Crear el esquema si no existe
CREATE SCHEMA IF NOT EXISTS erp_magicvoice;

-- Tabla de Usuarios (Perfiles)
CREATE TABLE IF NOT EXISTS erp_magicvoice.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'control_calidad', 'recepcion', 'generador', 'editor', 'conta')),
    active BOOLEAN DEFAULT TRUE,
    confirmed BOOLEAN DEFAULT FALSE,
    fcm_token TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Órdenes (Pedidos)
CREATE TABLE IF NOT EXISTS erp_magicvoice.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    script_text TEXT,
    observations TEXT,
    delivery_due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDIENTE' CHECK (status IN ('PENDIENTE', 'EN_GENERACION', 'EDICION', 'EN_REVISION', 'AUDIO_LISTO', 'ENTREGADO', 'ANULADO')),
    generator_id UUID REFERENCES erp_magicvoice.users(id) ON DELETE SET NULL,
    editor_id UUID REFERENCES erp_magicvoice.users(id) ON DELETE SET NULL,
    script_file_url TEXT,
    base_audio_url TEXT,
    final_audio_url TEXT,
    project_file_url TEXT,
    generation_started_at TIMESTAMP WITH TIME ZONE,
    generation_ended_at TIMESTAMP WITH TIME ZONE,
    edition_started_at TIMESTAMP WITH TIME ZONE,
    edition_ended_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    country TEXT,
    price NUMERIC(10, 2),
    phone TEXT,
    payment_method TEXT,
    product TEXT,
    audio_muestra_url TEXT
);

-- Habilitar RLS (Opcional, según tu configuración inicial)
ALTER TABLE erp_magicvoice.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp_magicvoice.orders ENABLE ROW LEVEL SECURITY;

-- Política básica para permitir lectura a usuarios autenticados
-- (Esto puede variar según tus requerimientos específicos)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'orders' AND policyname = 'Permitir todo a autenticados'
    ) THEN
        CREATE POLICY "Permitir todo a autenticados" ON erp_magicvoice.orders FOR ALL TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Permitir lectura a autenticados'
    ) THEN
        CREATE POLICY "Permitir lectura a autenticados" ON erp_magicvoice.users FOR SELECT TO authenticated USING (true);
    END IF;
END $$;
